name: Install and Test

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          curl -Ss https://raw.githubusercontent.com/OneAutumnMango/zsh-configs/master/setup.sh | sh
      
      - name: Verify ZSH
        run: exec zsh

      - name: Verify Starship
        run: exec starship init zsh

      - name: Verify Zoxide
        run: exec zoxide init zsh

      - name: Verify Files
        run: |
          echo "Checking ~/.zsh_aliases"
          [ -f ~/.zsh_aliases ]
          echo "Checking ~/.zsh_functions"
          [ -f ~/.zsh_functions ]
          echo "Checking ~/.zshrc"
          [ -f ~/.zshrc ]
          echo "Checking ~/.gitconfig"
          [ -f ~/.gitconfig ]
          echo "Checking ~/.config/starship.toml"
          [ -f ~/.config/starship.toml ]


              
