name: Install and Test

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run install script
        run: |
          if [ "${ACT}" = "true" ]; then
            sh setup.sh
          else
            curl -sS https://raw.githubusercontent.com/OneAutumnMango/zsh-configs/main/setup.sh | sh
          fi

      - name: Verify Zsh
        run:
          command -v zsh >/dev/null 2>&1 && echo "zsh is installed" || exit 1

      - name: Verify Starship
        run: exec starship init zsh

      - name: Verify Zoxide
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          exec zoxide init zsh

      - name: Verify Files
        run: |
          set -e
          [ -f "$HOME/.zsh_aliases" ]          && echo "  $HOME/.zsh_aliases Found" || { echo "  ❌ Missing ($HOME/.zsh_aliases)";          ls -l "$HOME" || true; exit 1; }
          [ -f "$HOME/.zsh_functions" ]        && echo "  $HOME/.zsh_functions Found" || { echo "  ❌ Missing ($HOME/.zsh_functions)";        ls -l "$HOME" || true; exit 1; }
          [ -f "$HOME/.zshrc" ]                && echo "  $HOME/.zshrc Found" || { echo "  ❌ Missing ($HOME/.zshrc)";                ls -l "$HOME" || true; exit 1; }
          [ -f "$HOME/.gitconfig" ]            && echo "  $HOME/.gitconfig Found" || { echo "  ❌ Missing ($HOME/.gitconfig)";            ls -l "$HOME" || true; exit 1; }
          [ -f "$HOME/.config/starship.toml" ] && echo "  $HOME/.config/starship.toml Found" || { echo "  ❌ Missing ($HOME/.config/starship.toml)"; ls -l "$HOME/.config" || true; exit 1; }

